[package]
name = "disk-read-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
curl = "0.4.47"
rand = "0.8.5"
rand_xorshift = "0.3.0"

[profile.release]
opt-level = 3
